### ISSUE TITLE
Fix sprint 2 results

### ISSUE THREAD

**Issue by jchodera** [FoldingAtHome/covid-moonshot#15]
cc: https://github.com/FoldingAtHome/covid-moonshot/pull/13#issuecomment-683188765

From @PantherX:
> I spotted this in the purchasing CSV file where row 8 has an extra column due to , similar to EN300-382173 and not sure where it will be imported into but an option would be to add a column "Notes" and while it can be blank for all rows (simply have , at the end of all those rows), it will be populated for row 8 😃

We should fix that in a PR.

**Comment by PantherX** [comment]
FYI, can this please be closed as the issue has been resolved 😄
